export const STORE_LOCAL_FOOTPRINT_WIDTH = 5;
export const STORE_LOCAL_FOOTPRINT_DEPTH = 5;

export const STORE_LOCAL_HALF_WIDTH = STORE_LOCAL_FOOTPRINT_WIDTH / 2;
export const STORE_LOCAL_HALF_DEPTH = STORE_LOCAL_FOOTPRINT_DEPTH / 2;

